<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Template;

class TemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $templates = [
            ['id' => 1, 'name' => 'Article Generator', 'icon' => '<i class="fa-solid fa-file-lines main-icon"></i>', 'description' => 'Turn a title and outline text into a fully complete high quality article within seconds', 'template_code' => 'KPAQQ', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'article-generator', 'type' => 'original'],
            ['id' => 2, 'name' => 'Content Rewriter', 'icon' => '<i class="fa-solid fa-square-check main-icon"></i>', 'description' => 'Take a piece of content and rewrite it to make it more interesting, creative, and engaging', 'template_code' => 'WCZGL', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'content-rewriter', 'type' => 'original'],
            ['id' => 3, 'name' => 'Paragraph Generator', 'icon' => '<i class="fa-solid fa-line-columns main-icon"></i>', 'description' => 'Generate paragraphs about any topic including a keyword and in a specific tone of voice', 'template_code' => 'JXRZB', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'paragraph-generator', 'type' => 'original'],
            ['id' => 4, 'name' => 'Talking Points', 'icon' => '<i class="fa-solid fa-list-check main-icon"></i>', 'description' => 'Write short, simple and informative points for the subheadings of your article', 'template_code' => 'VFWSQ', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'talking-points', 'type' => 'original'],
            ['id' => 5, 'name' => 'Pros & Cons', 'icon' => '<i class="fa-solid fa-code-compare main-icon"></i>', 'description' => 'Write the pros and cons of a product, service or website for your blog article', 'template_code' => 'OPYAB', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'pros-and-cons', 'type' => 'original'],
            ['id' => 6, 'name' => 'Blog Titles', 'icon' => '<i class="fa-solid fa-message-text blog-icon"></i>', 'description' => 'Nobody wants to read boring blog titles, generate catchy blog titles with this tool', 'template_code' => 'WGKYP', 'status' => true, 'professional' => false, 'group' => 'blog', 'slug' => 'blog-titles', 'type' => 'original'],
            ['id' => 7, 'name' => 'Blog Section', 'icon' => '<i class="fa-solid fa-message-lines blog-icon"></i>', 'description' => 'Write a full blog section (few paragraphs) about a subheading of your article', 'template_code' => 'EEKZF', 'status' => true, 'professional' => false, 'group' => 'blog', 'slug' => 'blog-section', 'type' => 'original'],
            ['id' => 8, 'name' => 'Blog Ideas', 'icon' => '<i class="fa-solid fa-message-dots blog-icon"></i>', 'description' => 'The perfect tool to start writing great articles. Generate creative ideas for your next post', 'template_code' => 'KDGOX', 'status' => true, 'professional' => false, 'group' => 'blog', 'slug' => 'blog-ideas', 'type' => 'original'],
            ['id' => 9, 'name' => 'Blog Intros', 'icon' => '<i class="fa-solid fa-message-exclamation blog-icon"></i>', 'description' => 'Write an intro that will entice your visitors to read more about your article', 'template_code' => 'TZTYR', 'status' => true, 'professional' => false, 'group' => 'blog', 'slug' => 'blog-intros', 'type' => 'original'],
            ['id' => 10, 'name' => 'Blog Conclusion', 'icon' => '<i class="fa-solid fa-message-check blog-icon"></i>', 'description' => 'End your blog articles with an engaging conclusion paragraph', 'template_code' => 'ZGUKM', 'status' => true, 'professional' => false, 'group' => 'blog', 'slug' => 'blog-conclusion', 'type' => 'original'],
            ['id' => 11, 'name' => 'Summarize Text', 'icon' => '<i class="fa-solid fa-file-contract main-icon"></i>', 'description' => 'Summmarize any text in a short and easy to understand concise way', 'template_code' => 'OMMEI', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'summarize-text', 'type' => 'original'],
            ['id' => 12, 'name' => 'Product Description', 'icon' => '<i class="fa-solid fa-list-check main-icon"></i>', 'description' => 'Write the description about your product and why it worth it', 'template_code' => 'HXLNA', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'product-description', 'type' => 'original'],
            ['id' => 13, 'name' => 'Startup Name Generator', 'icon' => '<i class="fa-solid fa-lightbulb-on main-icon"></i>', 'description' => 'Generate cool, creative, and catchy names for your startup in seconds', 'template_code' => 'DJSVM', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'startup-name-generator', 'type' => 'original'],
            ['id' => 14, 'name' => 'Product Name Generator', 'icon' => '<i class="fa-solid fa-box-circle-check main-icon"></i>', 'description' => 'Create creative product names from examples words', 'template_code' => 'IXKBE', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'product-name-generator', 'type' => 'original'],
            ['id' => 15, 'name' => 'Meta Description', 'icon' => '<i class="fa-solid fa-memo-circle-info web-icon"></i>', 'description' => 'Write SEO-optimized meta description based on a description', 'template_code' => 'JCDIK', 'status' => true, 'professional' => false, 'group' => 'web', 'slug' => 'meta-description', 'type' => 'original'],
            ['id' => 16, 'name' => 'FAQs', 'icon' => '<i class="fa-solid fa-message-question web-icon"></i>', 'description' => 'Generate frequently asked questions based on your product description', 'template_code' => 'SZAUF', 'status' => true, 'professional' => false, 'group' => 'web', 'slug' => 'faqs', 'type' => 'original'],
            ['id' => 17, 'name' => 'FAQ Answers', 'icon' => '<i class="fa-solid fa-messages-question web-icon"></i>', 'description' => 'Generate creative answers to questions (FAQs) about your business or website', 'template_code' => 'BFENK', 'status' => true, 'professional' => false, 'group' => 'web', 'slug' => 'faq-answers', 'type' => 'original'],
            ['id' => 18, 'name' => 'Testimonials / Reviews', 'icon' => '<i class="fa-solid fa-star-sharp-half-stroke web-icon"></i>', 'description' => 'Add social proof to your website by generating user testimonials', 'template_code' => 'XLGPP', 'status' => true, 'professional' => false, 'group' => 'web', 'slug' => 'testimonials', 'type' => 'original'],
            ['id' => 19, 'name' => 'Facebook Ads', 'icon' => '<i class="fa-brands fa-facebook social-icon"></i>', 'description' => 'Write Facebook ads that engage your audience and deliver a high conversion rate', 'template_code' => 'CTMNI', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'facebook-ads', 'type' => 'original'],
            ['id' => 20, 'name' => 'Video Descriptions', 'icon' => '<i class="fa-brands fa-youtube video-icon"></i>', 'description' => 'Write compelling YouTube descriptions to get people interested in your video', 'template_code' => 'ZLKSP', 'status' => true, 'professional' => false, 'group' => 'video', 'slug' => 'video-descriptions', 'type' => 'original'],
            ['id' => 21, 'name' => 'Video Titles', 'icon' => '<i class="fa-brands fa-youtube video-icon"></i>', 'description' => 'Write a compelling YouTube video title to catch everyones attention', 'template_code' => 'OJIOV', 'status' => true, 'professional' => false, 'group' => 'video', 'slug' => 'video-titles', 'type' => 'original'],
            ['id' => 22, 'name' => 'Youtube Tags Generator', 'icon' => '<i class="fa-brands fa-youtube video-icon"></i>', 'description' => 'Generate SEO-optimized YouTube tags / keywords for your video', 'template_code' => 'ECNVU', 'status' => true, 'professional' => false, 'group' => 'video', 'slug' => 'youtube-tags-generator', 'type' => 'original'],
            ['id' => 23, 'name' => 'Instagram Captions', 'icon' => '<i class="fa-brands fa-instagram social-icon"></i>', 'description' => 'Grab attention with catchy captions for your Instagram posts', 'template_code' => 'EOASR', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'instagram-captions', 'type' => 'original'],
            ['id' => 24, 'name' => 'Instagram Hashtags Generator', 'icon' => '<i class="fa-brands fa-instagram social-icon"></i>', 'description' => 'Find the best hashtags to use for your Instagram posts', 'template_code' => 'IEMBM', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'instagram-hashtags', 'type' => 'original'],
            ['id' => 25, 'name' => 'Social Media Post (Personal)', 'icon' => '<i class="fa-solid fa-thumbs-up social-icon"></i>', 'description' => 'Write a social media post for yourself to be published on any platform', 'template_code' => 'CKOHL', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'social-post-personal', 'type' => 'original'],
            ['id' => 26, 'name' => 'Social Media Post (Business)', 'icon' => '<i class="fa-solid fa-thumbs-up social-icon"></i>', 'description' => 'Write a post for your business to be published on any social media platform', 'template_code' => 'ABWGU', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'social-post-business', 'type' => 'original'],
            ['id' => 27, 'name' => 'Facebook Headlines', 'icon' => '<i class="fa-brands fa-facebook social-icon"></i>', 'description' => 'Write catchy and convincing headlines to make your Facebook Ads stand out', 'template_code' => 'HJYJZ', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'facebook-headlines', 'type' => 'original'],
            ['id' => 28, 'name' => 'Google Ads Headlines', 'icon' => '<i class="fa-brands fa-google social-icon"></i>', 'description' => 'Write catchy 30-character headlines to promote your product with Google Ads', 'template_code' => 'SGZTW', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'google-headlines', 'type' => 'original'],
            ['id' => 29, 'name' => 'Google Ads Description', 'icon' => '<i class="fa-brands fa-google social-icon"></i>', 'description' => 'Write a Google Ads description that makes your ad stand out and generates leads', 'template_code' => 'YQAFG', 'status' => true, 'professional' => false, 'group' => 'social', 'slug' => 'google-ads', 'type' => 'original'],
            ['id' => 30, 'name' => 'Problem-Agitate-Solution', 'icon' => '<i class="fa-solid fa-copyright web-icon"></i>', 'description' => 'Generate one of most effective copywriting formula for your business', 'template_code' => 'BGXJE', 'status' => true, 'professional' => false, 'group' => 'web', 'slug' => 'problem-agitate-solution', 'type' => 'original'],
            ['id' => 31, 'name' => 'Academic Essay', 'icon' => '<i class="fa-solid fa-scroll-old main-icon"></i>', 'description' => 'Create creative academic essays for various subjects just in a second', 'template_code' => 'SXQBT', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'academic-essay', 'type' => 'original'],
            ['id' => 32, 'name' => 'Welcome Email', 'icon' => '<i class="fa-solid fa-envelope-open-text email-icon"></i>', 'description' => 'Create welcome emails for your customers', 'template_code' => 'RLXGB', 'status' => true, 'professional' => false, 'group' => 'email', 'slug' => 'email-welcome', 'type' => 'original'],
            ['id' => 33, 'name' => 'Cold Email', 'icon' => '<i class="fa-solid fa-mailbox email-icon"></i>', 'description' => 'Create professional cold emails with the help of AI', 'template_code' => 'RDJEZ', 'status' => true, 'professional' => false, 'group' => 'email', 'slug' => 'email-cold', 'type' => 'original'],
            ['id' => 34, 'name' => 'Follow-Up Email', 'icon' => '<i class="fa-solid fa-reply-all email-icon"></i>', 'description' => 'Create professional email follow up with just few clicks', 'template_code' => 'XVNNQ', 'status' => true, 'professional' => false, 'group' => 'email', 'slug' => 'email-follow-up', 'type' => 'original'],
            ['id' => 35, 'name' => 'Creative Stories', 'icon' => '<i class="fa-solid fa-books main-icon"></i>', 'description' => 'Allow AI to generate creative stories for you based on input text', 'template_code' => 'PAKMF', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'creative-stories', 'type' => 'original'],
            ['id' => 36, 'name' => 'Grammar Checker', 'icon' => '<i class="fa-solid fa-spell-check main-icon"></i>', 'description' => 'Make sure that there are no errors in your content', 'template_code' => 'OORHD', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => 'grammar-checker', 'type' => 'original'],
            ['id' => 37, 'name' => 'Summarize for 2nd Grader', 'icon' => '<i class="fa-solid fa-thought-bubble main-icon"></i>', 'description' => 'Summarize any complex content for a 2nd grader child', 'template_code' => 'SGJLU', 'status' => true, 'professional' => false, 'group' => 'text', 'slug' => '2nd-grader', 'type' => 'original'],
            ['id' => 38, 'name' => 'Video Scripts', 'icon' => '<i class="fa-solid fa-film video-icon"></i>', 'description' => 'Quickly create scripts for your videos and start shooting', 'template_code' => 'WISHV', 'status' => true, 'professional' => false, 'group' => 'video', 'slug' => 'video-scripts', 'type' => 'original'],
            ['id' => 39, 'name' => 'Amazon Product Description', 'icon' => '<i class="fa-brands fa-amazon other-icon"></i>', 'description' => 'Create attention grabbing amazon product description', 'template_code' => 'WISTT', 'status' => true, 'professional' => false, 'group' => 'other', 'slug' => 'amazon-product', 'type' => 'original'],

        ];

        foreach ($templates as $template) {
            Template::updateOrCreate(['id' => $template['id']], $template);
        }
    }
}
